config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'
  resources :destinations, :events, :trips, :reservations, :transportations
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :destination
  belongs_to :event
  attr_accessible :date, :hour, :starting_point, :destination_id, :event_id

  validates :date, :presence => true
  validates :hour, :presence => true
  validates :starting_point, :presence => true,
                             :length   => { :minimum => 3 }
  validates :destination_id, :presence => true
  validates :event_id, :presence => true

  def due_date
    DateTime.new(date.year, date.month, date.day, 21, 0, 0).yesterday
  end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  # GET /trips
  # GET /trips.json
  def index
    @trips = Trip.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trips }
    end
  end

  # GET /trips/1
  # GET /trips/1.json
  def show
    @trip = Trip.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/new
  # GET /trips/new.json
  def new
    @trip = Trip.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trip }
    end
  end

  # GET /trips/1/edit
  def edit
    @trip = Trip.find(params[:id])
  end

  # POST /trips
  # POST /trips.json
  def create
    @trip = Trip.new(params[:trip])

    respond_to do |format|
      if @trip.save
        format.html { redirect_to "/trips", notice: 'Trip was successfully created.' }
        format.json { render json: @trip, status: :created, location: @trip }
      else
        format.html { render action: "new" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trips/1
  # PUT /trips/1.json
  def update
    @trip = Trip.find(params[:id])

    respond_to do |format|
      if @trip.update_attributes(params[:trip])
        format.html { redirect_to "/trips", notice: 'Trip was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trip.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trips/1
  # DELETE /trips/1.json
  def destroy
    @trip = Trip.find(params[:id])
    @trip.destroy

    respond_to do |format|
      format.html { redirect_to trips_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/views/trips/_form.html.erb
<%= form_for(@trip) do |f| %>
  <% if @trip.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trip.errors.count, "error") %> prohibited this trip from being saved:</h2>

      <ul>
      <% @trip.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br />
    <%= f.text_field :date, value: l(@trip.date || Date.tomorrow, format: "%d-%m-%Y"), readonly: true %>
  </div>
  <div class="field">
    <%= f.label :hour %><br />
    <%= f.text_field :hour, value: l(@trip.hour || Time.now.change({ hour: 9, min: 0 }), format: "%H:%M") %>
  </div>
  <div class="field">
    <%= f.label :starting_point %><br />
    <%= f.text_field :starting_point %>
  </div>
  <div class="field">
    <%= f.label :destination_id %><br />
    <%= f.select :destination_id, options_for_select(Destination.all.map { |d| [d.name, d.id] }, @trip.destination_id) %>
  </div>
  <div class="field">
    <%= f.label :event%><br />
    <%= f.select :event_id, options_for_select(Event.all.map { |e| [e.name, e.id] }, @trip.event_id) %>
  </div>
  <br/>
  <div class="actions" style="float: left; display: inline">
    <%= f.submit nil, class: 'btn btn-primary btn-success' %>
  </div>
<% end %>
<%= button_to 'Back', trips_path, class: "btn btn-black btn-primary", style: "display: inline; margin: -12px 0px 0px 20px;", method: :get %>

app/views/trips/edit.html.erb
<h1>Editing trip</h1>

<%= render 'form' %>

app/views/trips/index.html.erb
<section class="content">
  <h1 style="font-size:40px; color: #0C0F2E; font-weight: 600; text-align: center">Listing trips</h1><br/ ><br/ >
  <div class="row">
    <table class="table table-striped dataTable">
      <thead>
        <tr class="bg-box-green">
          <th style="font-size:17px">&nbsp;Date</th>
          <th style="font-size:17px">Hour</th>
          <th style="font-size:17px">Starting point</th>
          <th style="font-size:17px">Destination</th>
          <th style="font-size:17px">Event</th>
          <th style="font-size:17px"></th>
          <th style="font-size:17px"></th>
        </tr>
      </thead>
      <tbody aria-relevant="all" aria-live="polite" role="alert">
        <% @trips.sort { |a, b| a.date <=> b.date }.each do |trip| %>
          <tr class="bg-box-color">
            <td style="font-size:17px; width:120px; font-family: monospace; font-weight: 900;"><%= trip.date.strftime("%d-%m-%Y") %></td>
            <td style="font-size:17px; font-family: monospace; font-weight: 900;"><%= trip.hour.strftime("%H:%M") %></td>
            <td style="font-size:18px; font-family: monospace; font-weight: 900;"><%= trip.starting_point %></td>
            <td style="font-size:19px; font-family: monospace; font-weight: 900;"><%= trip.destination.name %></td>
            <td style="font-size:18px; font-family: monospace; font-weight: 900;"><%= trip.event.name %></td>
            <td style="font-size:15px; width:80px; font-family: monospace"><%= button_to 'Edit', edit_trip_path(trip), class: "btn btn-warning btn-primary", method: :get %></td>
            <td style="font-size:15px; width:80px; font-family: monospace"><%= button_to 'Destroy', trip, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-flat" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= button_to 'New Trip', new_trip_path, class: "btn btn-primary", method: :get %>
  </div>
</section>

<!-- page script -->
<!--script type="text/javascript">
  $(function () {
    $("#example1").dataTable();
    $('#example2').dataTable({
      "bPaginate": true,
      "bLengthChange": false,
      "bFilter": false,
      "bSort": true,
      "bInfo": true,
      "bAutoWidth": false
    });
  });
</script-->

app/views/trips/new.html.erb
<h1>New trip</h1>

<%= render 'form' %>

app/views/trips/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Date:</b>
  <%= @trip.date %>
</p>

<p>
  <b>Hour:</b>
  <%= @trip.hour.strftime("%H:%M") %>
</p>

<p>
  <b>Starting point:</b>
  <%= @trip.starting_point %>
</p>

<p>
  <b>Destination:</b>
  <%= @trip.destination.name %>
</p>

<p>
  <b>Event:</b>
  <%= @trip.event.name %>
</p>

<div>
  <%= button_to 'Edit', edit_trip_path(@trip), class: "btn btn-warning btn-primary", style: "float: left; display: block", method: :get %>
  <%= button_to 'Back', trips_path, class: "btn btn-black btn-primary", style: "float: left; display: block; margin-left: 10px", method: :get %>
</div>