config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'
  resources :destinations, :events, :trips, :reservations, :transportations
end

app/models/transportation.rb
class Transportation < ActiveRecord::Base
  has_many :trips
  attr_accessible :description, :priority

  validates :description, presence: true, length: { minimum: 10 }
  validates :priority,    presence: true, numericality: { greater_than_or_equal_to: 1 }
end

app/controllers/transportations_controller.rb
class TransportationsController < ApplicationController
  # GET /transportations
  # GET /transportations.json
  def index
    @transportations = Transportation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @transportations }
    end
  end

  # GET /transportations/1
  # GET /transportations/1.json
  def show
    @transportation = Transportation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @transportation }
    end
  end

  # GET /transportations/new
  # GET /transportations/new.json
  def new
    @transportation = Transportation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @transportation }
    end
  end

  # GET /transportations/1/edit
  def edit
    @transportation = Transportation.find(params[:id])
  end

  # POST /transportations
  # POST /transportations.json
  def create
    @transportation = Transportation.new(params[:transportation])

    respond_to do |format|
      if @transportation.save
        format.html { redirect_to "/transportations", notice: 'Transportation was successfully created.' }
        format.json { render json: @transportation, status: :created, location: @transportation }
      else
        format.html { render action: "new" }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /transportations/1
  # PUT /transportations/1.json
  def update
    @transportation = Transportation.find(params[:id])

    respond_to do |format|
      if @transportation.update_attributes(params[:transportation])
        format.html { redirect_to "/transportations", notice: 'Transportation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @transportation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transportations/1
  # DELETE /transportations/1.json
  def destroy
    @transportation = Transportation.find(params[:id])
    @transportation.destroy

    respond_to do |format|
      format.html { redirect_to "/transportations", notice: 'Transportation was successfully deleted.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/transportations_helper.rb
module TransportationsHelper
end

app/views/transportations/_form.html.erb
<%= form_for(@transportation) do |f| %>
  <% if @transportation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transportation.errors.count, "error") %> prohibited this transportation from being saved:</h2>

      <ul>
      <% @transportation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :priority %><br/ >
    <%= f.select :priority, options_for_select((1..Transportation.count + 1).to_a - Transportation.all.map { |transportation| transportation.priority unless transportation == @transportation }, @transportation.priority) %>
  </div>
  <div class="field">
    <%= f.label :description %><br/ >
    <%= f.text_field :description %>
  </div>
  <br/ >
  <div class="actions"  style="float: left; display: inline">
    <%= f.submit nil, class: 'btn btn-primary btn-success' %>
  </div>
<% end %>
<%= button_to 'Back', transportations_path, class: "btn btn-black btn-primary", style: "display: inline; margin: -12px 0px 0px 20px;", method: :get %>

app/views/transportations/edit.html.erb
<h1>Editing transportation</h1>

<%= render 'form' %>

app/views/transportations/index.html.erb
<section class="content">
  <h1 style="font-size:40px; color: #0C0F2E; font-weight: 600; text-align: center">Listing transportations</h1><br/ ><br/ >
  <div class="row">
    <table class="table table-striped dataTable">
      <thead>
        <tr class="bg-box-light-blue">
          <th>Priority</th>
          <th>Description</th>
          <th></th>
          <th></th>
        </tr>
      </thead>
      <tbody aria-relevant="all" aria-live="polite" role="alert">
        <% @transportations.sort { |a, b| a.priority <=> b.priority }.each do |transportation| %>
          <tr class="bg-box-color">
            <td style="font-size: 25px; width: 78px; font-weight: 800; font-family: courier;" align="center"><%= transportation.priority %></td>
            <td style="font-size: 22px; font-family: blagovest;"><%= transportation.description %></td>
            <td style="width: 80px;"><%= button_to 'Edit', edit_transportation_path(transportation), class: "btn btn-warning btn-primary", method: :get %></td>
            <td style="width: 80px;"><%= button_to 'Destroy', transportation, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-flat" %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= button_to 'New Transportation', new_transportation_path, class: "btn btn-primary", method: :get %>
  </div>
</section>

app/views/transportations/new.html.erb
<h1>New transportation</h1>

<%= render 'form' %>

app/views/transportations/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Priority:</b>
  <%= @transportation.priority %>
</p>

<p>
  <b>Description:</b>
  <%= @transportation.description %>
</p>

<%= button_to 'Edit', edit_transportation_path(@transportation), class: "btn btn-black btn-primary btn-warning", style: "float: left; display: block", method: :get %>
<%= button_to 'Back', transportations_path, class: "btn btn-black btn-primary", style: "display: inline; margin: -2px 0px 0px 20px;", method: :get %>