config/routes.rb
Rails.application.routes.draw do

  root to: 'events#index'
  resources :destinations, :events, :trips, :reservations, :transportations
end

app/models/reservation.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    record.errors.add attribute, (options[:message] || "is not an email") unless
      value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
  end
end

class Reservation < ActiveRecord::Base
  belongs_to :transportation
  belongs_to :trip
  attr_accessible :additional_message, :attendance, :city_of_departure, :email, :name, :surname, :telephone, :trip_id, :transportation_id

  validates :name, presence: true, length: { minimum: 2 }
  validates :surname, presence: true, length: { minimum: 3 }
  validates :telephone, presence: true, format: { with: /\+?\(?\)?\/?\d+/, on: :create }
  validates :email, presence: true, email: true
  validates :city_of_departure, presence: true, length: { minimum: 3 }
  validates :attendance, inclusion: { in: [true, false] }
  validates :transportation_id, presence: true
  validates :trip_id, presence: true
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
  # GET /reservations
  # GET /reservations.json
  def index
    @reservations = Reservation.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reservations }
    end
  end

  # GET /reservations/1
  # GET /reservations/1.json
  def show
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/new
  # GET /reservations/new.json
  def new
    @reservation = Reservation.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @reservation }
    end
  end

  # GET /reservations/1/edit
  def edit
    @reservation = Reservation.find(params[:id])
  end

  # POST /reservations
  # POST /reservations.json
  def create
    @reservation = Reservation.new(params[:reservation])

    respond_to do |format|
      if @reservation.save
        format.html { redirect_to reservations_url, notice: 'Reservation was successfully created.' }
        format.json { render json: @reservation, status: :created, location: @reservation }
      else
        format.html { render action: "new" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reservations/1
  # PUT /reservations/1.json
  def update
    @reservation = Reservation.find(params[:id])

    respond_to do |format|
      if @reservation.update_attributes(params[:reservation])
        format.html { redirect_to reservations_url, notice: 'Reservation was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @reservation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reservations/1
  # DELETE /reservations/1.json
  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy

    respond_to do |format|
      format.html { redirect_to reservations_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/views/reservations/_form.html.erb
<%= form_for(@reservation) do |f| %>
  <% if @reservation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@reservation.errors.count, "error") %> prohibited this reservation from being saved:</h2>

      <ul>
      <% @reservation.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br/ >
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :surname %><br/ >
    <%= f.text_field :surname %>
  </div>
  <div class="field">
    <%= f.label :email %><br/ >
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :telephone %><br/ >
    <%= f.text_field :telephone %>
  </div>
  <div class="field">
    <%= f.label :city_of_departure %><br/ >
    <%= f.text_field :city_of_departure %>
  </div>
  <div class="field">
    <%= f.label :additional_message %><br/ >
    <%= f.text_field :additional_message %>
  </div>
  <div class="field">
    <%= f.label :trip %><br/ >
    <%= f.select :trip_id, options_for_select(Trip.all.map { |t| [Destination.find(t.destination_id).name + '  ' + t.date.strftime('%d-%m-%Y'), t.id] }, @reservation.trip_id) %>
  </div>
  <div class="field">
    <%= f.label :transportation %><br/ >
    <%= f.select :transportation_id, options_for_select(Transportation.all.map { |t| [t.description, t.id] }, @reservation.transportation_id) %>
  </div>
  <%= f.hidden_field :attendance, value: true %>
  <br/ >
  <div class="actions"  style="float: left; display: inline">
    <%= f.submit nil, class: 'btn btn-primary btn-success' %>
  </div>
<% end %>
<%= button_to 'Back', reservations_path, class: "btn btn-black btn-primary", style: "display: inline; margin: -12px 0px 0px 20px;", method: :get %>

app/views/reservations/edit.html.erb
<h1>Editing reservation</h1>

<%- attendance = true %><br/ >

<%= render 'form' %>

app/views/reservations/index.html.erb
<section class="content">
  <h1 style="font-size:40px; color: #0C0F2E; font-weight: 600; text-align: center">Listing reservations</h1><br/ ><br/ >
  <div class="row">
    <table class="table table-striped dataTable">
      <thead>
        <tr class="bg-box-purple">
          <th>Name</th>
          <th>Trip</th>
          <th>Email</th>
          <th>Telephone</th>
          <th>Transportation</th>
        </tr>
      </thead>
      <tbody aria-relevant="all" aria-live="polite" role="alert">
        <% @reservations.sort { |a, b| a.name + a.surname <=> b.name + b.surname }.each do |reservation| %>
          <tr class="bg-box-color">
            <td style="font-size:17px; width:220px; font-family: blagovest;"><%= "#{reservation.name} #{reservation.surname}" %></td>
            <td style="font-size:16px; font-family: blagovest;"><%= "#{Destination.find(reservation.trip.destination_id).name}: #{Trip.find(reservation.trip).date.strftime('%d-%m-%Y')}" %></td>
            <td style="font-size:17px; font-family: blagovest;"><%= reservation.email %></td>
            <td style="font-size:17px; font-family: courier; font-weight: 800;"><%= reservation.telephone %></td>
            <td style="font-size:16px; font-family: blagovest;"><%= Transportation.find(reservation.transportation_id).description %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <%= button_to 'New Reservation', new_reservation_path, class: "btn btn-primary", method: :get %>
  </div>
</section>

app/views/reservations/new.html.erb
<h1>New reservation</h1>

<%= render 'form' %>

app/views/reservations/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_reservation_path(@reservation) %> |
<%= link_to 'Back', reservations_path %>